package ex03.execption;

public class MultiCatch {
	public static void main(String[] args) {
		int x = 0, y  = result;
		
		try {
			System.out.println()
			x = new Scanner(Systen.in).nexInt
			y = new Scanner(Systen.in).nextInt;
			
			result = x / y;
			
			System.out.println(result);
		} 
		
		catch (ArithmeticExeption e)
			System.out.println()"";;

			
		}
	}

}
